### ISSUE TITLE
Fix broken link to Template:Documentation

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/wiki#1]
@MartijnBraam, what was that for?
See: https://wiki.postmarketos.org/wiki/Special:WantedPages

**Comment by MartijnBraam** [comment]
Template:Documentation is a template on wikipedia.org, I got that broken link from copying other templates from wikipedia which contain that reference

**Comment by ollieparanoid** [comment]
`Template:Documentation` on Wikipedia is quite complex, so I've created a `Template:Template` page, based on the ArchWiki page of the same name. That page is now used in the [Template:Infobox](https://wiki.postmarketos.org/wiki/Template:Infobox) page. The dead link is gone now.
