### ISSUE TITLE
Add chipset property in the infobox template

### ISSUE THREAD

**Issue by drebrez** [postmarketOS/wiki#13]
Right now there is some confusion, some pages in the `cpu` they have the `chipset` or only the information about the cpu itself.
If we have the `chipset` will be more clean, for example the N900 will have:
**Chipset** TI OMAP 3430
**CPU**  600 MHz Cortex-A8
**GPU** PowerVR SGX530

For example the Sony Xperia Z right now has:
**CPU**  1.5 GHz Qualcomm APQ8064+MDM9215M Quad Core
which is a mix of both.

**Comment by ollieparanoid** [comment]
Great idea!

**Comment by drebrez** [comment]
@ollieparanoid I've no idea how to modify the template, @MartijnBraam can you help?
I can help updating all the existing infoboxes of the various devices.

**Comment by ollieparanoid** [comment]
It should be possible by editing this template page:
https://wiki.postmarketos.org/wiki/Template:Infobox

**Comment by MartijnBraam** [comment]
Its actually this template: https://wiki.postmarketos.org/index.php?title=Template:Infobox_device

**Comment by ollieparanoid** [comment]
@drebrez: is there anything left to do, or can we close this issue?
