### ISSUE TITLE
Remove "Sidebar" page

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/wiki#2]
This got migrated from the old wiki, although we don't need it in the new wiki:
 https://wiki.postmarketos.org/wiki/Sidebar

@MartijnBraam: could you please delete it/give me rights so I can delete it myself (I'm planning to do quite some work on the wiki, so I'll probably need that anyway)?

**Comment by MartijnBraam** [comment]
I've given you admin permissions now, we probably should move some stuff in the mediawiki sidebar

**Comment by ollieparanoid** [comment]
The "Sidebar" page redirects to the MediaWiki Sidebar now.
