### ISSUE TITLE
GitHub login is broken

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/wiki#3]
Either fix this (preferred!) or remove it completely.

**Comment by MartijnBraam** [comment]
I've disabled it temporary and created this issue: https://github.com/LosFuzzys/MediaWiki-OAuth2-Github/issues/10

**Comment by ollieparanoid** [comment]
@PabloCastellano proposed to try out this extension instead:
https://www.mediawiki.org/wiki/Extension:OAuth2_Client

**Comment by ollieparanoid** [comment]
With whatever is enabled now, I get the following error:

> Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in /var/www/wiki.postmarketos.org/extensions/MW-OAuth2Client/vendors/oauth2-client/src/Provider/AbstractProvider.php on line 566 and defined in /var/www/wiki.postmarketos.org/extensions/MW-OAuth2Client/vendors/oauth2-client/src/Provider/AbstractProvider.php on line 737

**Comment by PabloCastellano** [comment]
I wrote a possible workaround on Matrix, which is updating the submodules.
@MartijnBraam did you have the opportunity to test it?

```
git submodule init
git submodule update
cd vendors/oauth2-client
git pull origin master
composer install
```

**Comment by MartijnBraam** [comment]
I've tried that but it doesn't actually fix the issue. I just get basically the same error after I flush some caches.

**Comment by ollieparanoid** [comment]
@PabloCastellano, thanks for finding that and thanks to @MartijnBraam for trying it out.

As I see it now, there is no plugin that just works for us. and people don't really seem to have a problem registering an account with the wiki. The only way we could fix this is by digging into the PHP code and maintaining the plugin ourselves, which doesn't seem to be worth it.

The broken GitHub login in the wiki was removed again and I'll close this issue. If someone would like to look further into this, please let us know and we'll reopen it.
