### ISSUE TITLE
Add a simple spam protection question in the wiki

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/wiki#4]
MediaWikis get spammed a lot by bots, so we could at least prevent the bots not targeting specific wikis by asking something project specific in the wiki registration.

Example:
> Which distribution is pmOS based on (without "Linux" at the end, all lower case)?

That is easy for someone who is interested in the project, but impossible for a bot without human interaction. [Example how Arch does it.](https://wiki.archlinux.org/index.php?title=Special:CreateAccount&returnto=Main+page)

@MartijnBraam, could you do that?

**Comment by ollieparanoid** [comment]
This extension does what we need for that task:
https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:QuestyCaptcha

I would *only* ask a question at registration time: `$wgCaptchaTriggers['createaccount']`, so spam bots can't register without human help. Once a human is involved, these questions are trivial to pass anyway, and we would need other measures.

**Comment by MartijnBraam** [comment]
Added the extension and the question

**Comment by ollieparanoid** [comment]
Thanks!
