### ISSUE TITLE
Mobile view: Responsive skin, responsive tables

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/wiki#5]
I haven't done much research here. But the Arch Wiki uses [this](https://www.mediawiki.org/wiki/Extension:MobileFrontend) extension, maybe that's also working fine for us.

**Comment by MartijnBraam** [comment]
I've installed the mobile frontend extension, it's also the one wikipedia uses.

**Comment by ollieparanoid** [comment]
Tested and working great, thanks!
